name:                haskpad-server
version:             0.1.0.0
github:              "cyoon1729/haskpad"
license:             BSD3
author:              "Chris Yoon"
maintainer:          "Chris Yoon"
copyright:           "2022 Chris Yoon"


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cyoon1729/haskpad#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- servant-server
- servant-websockets
- stm
- text
- uuid
- wai
- warp
- websockets

library:
  source-dirs: src

executables:
  haskpad-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskpad-server

tests:
  haskpad-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskpad-server
